#!/bin/bash
declare -A M
M["PROMPT_CORE_SYSTEM"]="CORE_SYSTEM_PROMPT"
M["SEED_SYSTEM_CONTEXT"]="SYSTEM_CONTEXT_SEED"
M["SEED_PERSONA_ADAPTER"]="PERSONA_ADAPTER_SEED"
M["SEED_PAPER_SUMMARY_MODULE"]="PAPER_SUMMARY_SEED"
M["SEED_SECTION_SUMMARY_MODULE"]="PAPER_SUMMARY_SECTIONS_SEED"
M["SEED_TRANSLATION_MODULE"]="CONTEXT_AWARE_TRANSLATION_SEED"
M["SEED_SIMPLE_TRANSLATION_MODULE"]="SIMPLE_TRANSLATION_SEED"
M["SEED_SENTENCE_TRANSLATION_MODULE"]="SENTENCE_TRANSLATION_SEED"
M["SEED_CHAT_MODULE"]="CHAT_GENERAL_SEED"
M["SEED_ADVERSARIAL_MODULE"]="ADVERSARIAL_CRITIQUE_SEED"
M["SEED_VISION_FIGURE_MODULE"]="VISION_FIGURE_SEED"
M["SEED_RECOMMENDATION_MODULE"]="PAPER_RECOMMENDATION_SEED"
M["PROMPT_DIRECT_DICT_TRANSLATE_SYSTEM"]="DICT_TRANSLATE_SYSTEM_PROMPT"
M["PROMPT_DIRECT_DICT_TRANSLATE_USER"]="DICT_TRANSLATE_LLM_PROMPT"
M["PROMPT_DIRECT_DICT_TRANSLATE_LONG_SYSTEM"]="DICT_TRANSLATE_LONG_SYSTEM_PROMPT"
M["PROMPT_DIRECT_DICT_TRANSLATE_LONG_USER"]="DICT_TRANSLATE_LONG_LLM_PROMPT"
M["PROMPT_PDF_SENTENCE_TRANSLATE"]="SENTENCE_TRANSLATE_FROM_PDF_PROMPT"
M["PROMPT_PDF_TERM_TRANSLATE"]="TRANSLATE_FROM_PDF_PROMPT"
M["PROMPT_PDF_TERM_EXPLAIN"]="EXPLAIN_FROM_PDF_PROMPT"
M["PROMPT_PDF_VISION_ANALYZE"]="VISION_ANALYZE_FIGURE_PROMPT"
M["PROMPT_PDF_ADVERSARIAL_CRITIQUE"]="ADVERSARIAL_CRITIQUE_FROM_PDF_PROMPT"
M["PROMPT_PDF_PAPER_SUMMARY"]="PAPER_SUMMARY_FROM_PDF_PROMPT"
M["PROMPT_PDF_CHAT_GENERAL"]="CHAT_GENERAL_FROM_PDF_PROMPT"
M["PROMPT_PDF_CHAT_WITH_FIGURE"]="CHAT_WITH_FIGURE_PROMPT"

DIRS="backend/app common tests inference-service"

for old in "${!M[@]}"; do
  new="${M[$old]}"
  for d in $DIRS; do
    if [ -d "$d" ]; then
      find "$d" -type f -name "*.py" -exec sed -i "s/$old/$new/g" {} +
    fi
  done
done
