#!/bin/bash
# Naming migration script

# Target directories
DIRS="backend/app inference-service common tests"

# Define mappings
declare -A MAPPINGS
MAPPINGS["CORE_SYSTEM_PROMPT"]="PROMPT_CORE_SYSTEM"
MAPPINGS["SYSTEM_CONTEXT_SEED"]="SEED_SYSTEM_CONTEXT"
MAPPINGS["PERSONA_ADAPTER_SEED"]="SEED_PERSONA_ADAPTER"
MAPPINGS["PAPER_SUMMARY_SEED"]="SEED_PAPER_SUMMARY_MODULE"
MAPPINGS["PAPER_SUMMARY_SECTIONS_SEED"]="SEED_SECTION_SUMMARY_MODULE"
MAPPINGS["CONTEXT_AWARE_TRANSLATION_SEED"]="SEED_TRANSLATION_MODULE"
MAPPINGS["SIMPLE_TRANSLATION_SEED"]="SEED_SIMPLE_TRANSLATION_MODULE"
MAPPINGS["SENTENCE_TRANSLATION_SEED"]="SEED_SENTENCE_TRANSLATION_MODULE"
MAPPINGS["CHAT_GENERAL_SEED"]="SEED_CHAT_MODULE"
MAPPINGS["ADVERSARIAL_CRITIQUE_SEED"]="SEED_ADVERSARIAL_MODULE"
MAPPINGS["VISION_FIGURE_SEED"]="SEED_VISION_FIGURE_MODULE"
MAPPINGS["PAPER_RECOMMENDATION_SEED"]="SEED_RECOMMENDATION_MODULE"

MAPPINGS["DICT_TRANSLATE_SYSTEM_PROMPT"]="PROMPT_DIRECT_DICT_TRANSLATE_SYSTEM"
MAPPINGS["DICT_TRANSLATE_LLM_PROMPT"]="PROMPT_DIRECT_DICT_TRANSLATE_USER"
MAPPINGS["DICT_TRANSLATE_LONG_SYSTEM_PROMPT"]="PROMPT_DIRECT_DICT_TRANSLATE_LONG_SYSTEM"
MAPPINGS["DICT_TRANSLATE_LONG_LLM_PROMPT"]="PROMPT_DIRECT_DICT_TRANSLATE_LONG_USER"
MAPPINGS["SENTENCE_TRANSLATE_FROM_PDF_PROMPT"]="PROMPT_PDF_SENTENCE_TRANSLATE"
MAPPINGS["TRANSLATE_FROM_PDF_PROMPT"]="PROMPT_PDF_TERM_TRANSLATE"
MAPPINGS["EXPLAIN_FROM_PDF_PROMPT"]="PROMPT_PDF_TERM_EXPLAIN"
MAPPINGS["VISION_ANALYZE_FIGURE_PROMPT"]="PROMPT_PDF_VISION_ANALYZE"
MAPPINGS["ADVERSARIAL_CRITIQUE_FROM_PDF_PROMPT"]="PROMPT_PDF_ADVERSARIAL_CRITIQUE"
MAPPINGS["PAPER_SUMMARY_FROM_PDF_PROMPT"]="PROMPT_PDF_PAPER_SUMMARY"
MAPPINGS["CHAT_GENERAL_FROM_PDF_PROMPT"]="PROMPT_PDF_CHAT_GENERAL"
MAPPINGS["CHAT_WITH_FIGURE_PROMPT"]="PROMPT_PDF_CHAT_WITH_FIGURE"

for old_name in "${!MAPPINGS[@]}"; do
    new_name="${MAPPINGS[$old_name]}"
    echo "Renaming $old_name to $new_name..."
    # Use find + sed for all files in DIRS
    find $DIRS -type f -name "*.py" -exec sed -i "s/$old_name/$new_name/g" {} +
done
