#!/bin/bash
# Revert naming migration script

# Target directories
DIRS="backend/app inference-service common tests"

# Define reverse mappings
declare -A MAPPINGS
MAPPINGS["PROMPT_CORE_SYSTEM"]="CORE_SYSTEM_PROMPT"
MAPPINGS["SEED_SYSTEM_CONTEXT"]="SYSTEM_CONTEXT_SEED"
MAPPINGS["SEED_PERSONA_ADAPTER"]="PERSONA_ADAPTER_SEED"
MAPPINGS["SEED_PAPER_SUMMARY_MODULE"]="PAPER_SUMMARY_SEED"
MAPPINGS["SEED_SECTION_SUMMARY_MODULE"]="PAPER_SUMMARY_SECTIONS_SEED"
MAPPINGS["SEED_TRANSLATION_MODULE"]="CONTEXT_AWARE_TRANSLATION_SEED"
MAPPINGS["SEED_SIMPLE_TRANSLATION_MODULE"]="SIMPLE_TRANSLATION_SEED"
MAPPINGS["SEED_SENTENCE_TRANSLATION_MODULE"]="SENTENCE_TRANSLATION_SEED"
MAPPINGS["SEED_CHAT_MODULE"]="CHAT_GENERAL_SEED"
MAPPINGS["SEED_ADVERSARIAL_MODULE"]="ADVERSARIAL_CRITIQUE_SEED"
MAPPINGS["SEED_VISION_FIGURE_MODULE"]="VISION_FIGURE_SEED"
MAPPINGS["SEED_RECOMMENDATION_MODULE"]="PAPER_RECOMMENDATION_SEED"

MAPPINGS["PROMPT_DIRECT_DICT_TRANSLATE_SYSTEM"]="DICT_TRANSLATE_SYSTEM_PROMPT"
MAPPINGS["PROMPT_DIRECT_DICT_TRANSLATE_USER"]="DICT_TRANSLATE_LLM_PROMPT"
MAPPINGS["PROMPT_DIRECT_DICT_TRANSLATE_LONG_SYSTEM"]="DICT_TRANSLATE_LONG_SYSTEM_PROMPT"
MAPPINGS["PROMPT_DIRECT_DICT_TRANSLATE_LONG_USER"]="DICT_TRANSLATE_LONG_LLM_PROMPT"
MAPPINGS["PROMPT_PDF_SENTENCE_TRANSLATE"]="SENTENCE_TRANSLATE_FROM_PDF_PROMPT"
MAPPINGS["PROMPT_PDF_TERM_TRANSLATE"]="TRANSLATE_FROM_PDF_PROMPT"
MAPPINGS["PROMPT_PDF_TERM_EXPLAIN"]="EXPLAIN_FROM_PDF_PROMPT"
MAPPINGS["PROMPT_PDF_VISION_ANALYZE"]="VISION_ANALYZE_FIGURE_PROMPT"
MAPPINGS["PROMPT_PDF_ADVERSARIAL_CRITIQUE"]="ADVERSARIAL_CRITIQUE_FROM_PDF_PROMPT"
MAPPINGS["PROMPT_PDF_PAPER_SUMMARY"]="PAPER_SUMMARY_FROM_PDF_PROMPT"
MAPPINGS["PROMPT_PDF_CHAT_GENERAL"]="CHAT_GENERAL_FROM_PDF_PROMPT"
MAPPINGS["PROMPT_PDF_CHAT_WITH_FIGURE"]="CHAT_WITH_FIGURE_PROMPT"

for old_name in "${!MAPPINGS[@]}"; do
    new_name="${MAPPINGS[$old_name]}"
    echo "Reverting $old_name to $new_name..."
    # Update seed file first to be safe
    sed -i "s/$old_name/$new_name/g" common/dspy_seed_prompt.py
    # Then all other files
    find $DIRS -type f -name "*.py" -exec sed -i "s/$old_name/$new_name/g" {} +
done
