# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  GREETING: Hello, world!

tasks:
  default:
    desc: Print a greeting message
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  redis:
    desc: "Start Redis container"
    cmds:
      - docker run -d --name paper-terrace-redis -p 6379:6379 redis:latest || docker start paper-terrace-redisU

  run:
    desc: "Run local server"
    cmds:
      - uv run uvicorn src.main:app --reload

  build:
    desc: "Build frontend"
    cmds:
      - cd frontend && npm run dev
