# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

dotenv: [".env"]

vars:
  GREETING: Hello, world!
  PROJECT_ID: gen-lang-client-0800253336
  REGION: asia-northeast1

tasks:
  default:
    desc: Print a greeting message
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  redis:
    desc: "Start Redis container"
    cmds:
      - docker run -d --name paper-terrace-redis -p 6379:6379 redis:latest || docker start paper-terrace-redisU

  run:
    desc: "Run local server"
    cmds:
      - PYTHONUNBUFFERED=1 uv run uvicorn src.main:app 2>&1 | tee logs/server.log

  build:
    desc: "Build frontend"
    cmds:
      - cd frontend && npm run build

  dev:
    desc: "Run frontend dev server"
    cmds:
      - cd frontend && npm run dev

  read:info:
    desc: "Run local server"
    cmds:
      - gcloud run services logs read paperterrace --limit=100

  read:error:
    desc: "Run local server"
    cmds:
      - gcloud logging read 'resource.type="cloud_run_revision" AND resource.labels.service_name="paperterrace" AND severity>=ERROR' --limit=50 --format=json

  tail:info:
    desc: "Run local server"
    cmds:
      - gcloud beta run services logs tail paperterrace

  tail:error:
    desc: "Run local server"
    cmds:
      - gcloud logging tail 'resource.type="cloud_run_revision" AND resource.labels.service_name="paperterrace" AND severity>=ERROR' --limit=50 --format=json

  get_iam:
    desc: "Get IAM policy"
    cmds:
      - gcloud run services get-iam-policy paperterrace

  add_all_users:
    desc: "Add auth"
    cmds:
      - gcloud run services add-iam-policy-binding paperterrace --member="allUsers" --role="roles/run.invoker"

  remove_all_users:
    desc: "Remove IAM policy"
    cmds:
      - gcloud run services remove-iam-policy-binding paperterrace --member="allUsers" --role="roles/run.invoker"

  db:stop:
    desc: Stop Cloud SQL instance (save cost)
    cmds:
      - gcloud sql instances patch paperterrace-db --activation-policy=NEVER

  db:start:
    desc: Start Cloud SQL instance
    cmds:
      - gcloud sql instances patch paperterrace-db --activation-policy=ALWAYS

  all_stop:
    desc: Stop all services
    deps: [remove_all_users, db:stop]

  deploy:
    desc: Full deploy including infra checks
    cmds:
      - ./deploy.sh
  deploy:fast:
    desc: Deploy application code fast (skips infra checks)
    cmds:
      - ./deploy.sh --skip-infra

  db:wait:
    desc: Wait for Cloud SQL to be RUNNABLE
    cmds:
      - |
        echo "Waiting for Cloud SQL to be RUNNABLE..."
        for i in 1 2 3 4 5 6; do
          STATUS=$(gcloud sql instances describe paperterrace-db \
            --format="value(state)")
          echo "Current state: $STATUS"
          if [ "$STATUS" = "RUNNABLE" ]; then
            echo "Cloud SQL is ready"
            exit 0
          fi
          sleep 30
        done
        echo "Cloud SQL did not become RUNNABLE"
        exit 1

  start:
    desc: start db and deploy
    deps:
      - db:start
      - db:wait
      - deploy

  ruff:
    desc: "Run ruff"
    cmds:
      - uv run ruff check --fix .

  cache_clear:
    desc: "Clear cache"
    cmds:
      - sqlite3 ocr_reader.db "DELETE FROM ocr_reader;"
      - rm -rf src/static/paper_images/*

  # ============================================================================
  # Staging Environment Tasks
  # ============================================================================

  staging:deploy:
    desc: "Deploy Staging Environment (Terraform enable_staging=true)"
    cmds:
      - echo "Deploying Staging Environment..."
      - cd terraform && TF_VAR_gemini_api_key=$GEMINI_API_KEY TF_VAR_db_password=$DB_PASSWORD terraform apply -var="enable_staging=true" -auto-approve
      - echo "Staging Environment Deployed."
      - echo "Initial App Deploy to Staging..."
      - gcloud builds submit --tag {{.REGION}}-docker.pkg.dev/{{.PROJECT_ID}}/paperterrace/app:latest
      - gcloud run deploy paperterrace-staging --image {{.REGION}}-docker.pkg.dev/{{.PROJECT_ID}}/paperterrace/app:latest --region {{.REGION}} --allow-unauthenticated

  staging:destroy:
    desc: "Destroy Staging Environment (Terraform enable_staging=false)"
    cmds:
      - echo "Destroying Staging Environment..."
      - cd terraform && TF_VAR_gemini_api_key=$GEMINI_API_KEY TF_VAR_db_password=$DB_PASSWORD terraform apply -var="enable_staging=false" -auto-approve
      - echo "Staging Environment Destroyed. Database 'paperterrace_staging' removed."

  staging:logs:
    desc: "Read Staging logs"
    cmds:
      - gcloud run services logs read paperterrace-staging --limit=100
