# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

dotenv: ["secrets/.env"]

vars:
  PROJECT_ID: '{{.PROJECT_ID | default "gen-lang-client-0800253336"}}'
  REGION: '{{.REGION | default "asia-northeast1"}}'

  # Resource Configurations from JSON
  BE_CPU:
    {
      sh: 'python3 -c ''import json; print(json.load(open("config/resources.json"))["backend"]["cpu"])''',
    }
  BE_MEM:
    {
      sh: 'python3 -c ''import json; print(json.load(open("config/resources.json"))["backend"]["memory"])''',
    }
  BE_STG_CPU:
    {
      sh: 'python3 -c ''import json; print(json.load(open("config/resources.json"))["backend_staging"]["cpu"])''',
    }
  BE_STG_MEM:
    {
      sh: 'python3 -c ''import json; print(json.load(open("config/resources.json"))["backend_staging"]["memory"])''',
    }

  INF_CPU:
    {
      sh: 'python3 -c ''import json; print(json.load(open("config/resources.json"))["inference"]["cpu"])''',
    }
  INF_MEM:
    {
      sh: 'python3 -c ''import json; print(json.load(open("config/resources.json"))["inference"]["memory"])''',
    }
  INF_STG_CPU:
    {
      sh: 'python3 -c ''import json; print(json.load(open("config/resources.json"))["inference_staging"]["cpu"])''',
    }
  INF_STG_MEM:
    {
      sh: 'python3 -c ''import json; print(json.load(open("config/resources.json"))["inference_staging"]["memory"])''',
    }
  INF_STG_WORKERS:
    {
      sh: 'python3 -c ''import json; print(json.load(open("config/resources.json"))["inference_staging"].get("batch_parallel_workers", 2))''',
    }

  INF_WORKERS:
    {
      sh: 'python3 -c ''import json; print(json.load(open("config/resources.json"))["inference"].get("batch_parallel_workers", 2))''',
    }

  BUILD_MACHINE:
    {
      sh: 'python3 -c ''import json; print(json.load(open("config/resources.json"))["build"]["machine_type"])''',
    }

tasks:
  # ============================================================================
  # Development Tasks
  # ============================================================================

  default:
    desc: "Show available tasks"
    cmds:
      - task --list
    silent: true

  setup:
    desc: "Setup development environment"
    cmds:
      - echo "🔧 Setting up development environment..."
      - task: redis
      - echo "✅ Development environment ready!"

  redis:
    desc: "Start Redis container for local development"
    cmds:
      - docker run -d --name paper-terrace-redis -p 6379:6379 redis:latest || docker start paper-terrace-redis

  run:
    desc: "Run backend server with hot reload"
    cmds:
      - mkdir -p logs
      - PYTHONUNBUFFERED=1 uv run --directory backend env PYTHONPATH=.:.. uvicorn app.main:app --reload --host 0.0.0.0 --port 8080 | tee -a logs/local.log

  dev:
    desc: "Run frontend dev server"
    cmds:
      - npm run dev
    dir: frontend

  dev:full:
    desc: "Run both backend and frontend in parallel"
    deps: [redis]
    cmds:
      - echo "🚀 Starting full development environment..."
      - |
        # Start backend in background
        PYTHONUNBUFFERED=1 uv run --directory backend env PYTHONPATH=.:.. uvicorn app.main:app --reload --host 0.0.0.0 --port 8080 &
        BACKEND_PID=$!

        # Start frontend in background  
        cd frontend && npm run dev &
        FRONTEND_PID=$!

        echo "Backend PID: $BACKEND_PID"
        echo "Frontend PID: $FRONTEND_PID"
        echo "Press Ctrl+C to stop both services"

        # Wait for interrupt
        trap "kill $BACKEND_PID $FRONTEND_PID 2>/dev/null; exit" INT
        wait

  build:
    desc: "Build frontend for production"
    cmds:
      - npm run build
    dir: frontend

  test:backend:
    desc: "Run backend tests"
    cmds:
      - uv run --directory backend env PYTHONPATH=.:.. pytest -n auto

  test:inference:
    desc: "Run inference service tests"
    cmds:
      - uv run --directory inference-service env PYTHONPATH=.:.. pytest -n auto

  test:redis:
    desc: "Run redis provider tests"
    cmds:
      - uv run --directory redis_provider env PYTHONPATH=.:.. pytest

  test:frontend:
    desc: "Run frontend tests (Vitest)"
    cmds:
      - cd frontend && npm run test

  test:
    desc: "Run affected tests for all components (Optimized)"
    cmds:
      - task: test:backend
      - task: test:inference
      - task: test:redis
      - task: test:frontend

  test:all:
    desc: "Run all tests for all components"
    cmds:
      - uv run --directory backend env PYTHONPATH=.:.. pytest -n auto
      - uv run --directory inference-service env PYTHONPATH=.:.. pytest -n auto
      - uv run --directory redis_provider env PYTHONPATH=.:.. pytest
      - cd frontend && npm run test

  lint:
    desc: "Run linting and formatting for all components"
    cmds:
      - echo "🔍 Running biome check..."
      - npx biome check --write frontend/ common/ redis_provider/
      - echo "🔍 Running backend linting..."
      - uv run --directory backend ruff check --fix .
      - echo "🔍 Running inference-service linting..."
      - uv run --directory inference-service ruff check --fix .
      - echo "🔍 Running common & shared linting..."
      - uv run --directory backend ruff check --fix ../common
      - uv run --directory redis_provider ruff check --fix .
      - echo "🔍 Running frontend linting..."
      - cd frontend && npm run lint

  clean:
    desc: "Clean cache and temporary files"
    cmds:
      - echo "🧹 Cleaning cache..."
      - rm -rf backend/.ruff_cache backend/__pycache__ backend/app/__pycache__
      - rm -rf frontend/node_modules/.cache frontend/dist
      - sqlite3 ocr_reader.db "DELETE FROM ocr_reader;" 2>/dev/null || true
      - rm -rf backend/app/static/paper_images/* 2>/dev/null || true
      - rm -rf logs/*.log
      - echo "✅ Cache cleared!"

  # ============================================================================
  # Production Tasks
  # ============================================================================

  # ============================================================================
  # Database Tasks
  # ============================================================================

  db:start:
    desc: "Start Cloud SQL instance"
    cmds:
      - echo "🔄 Starting Cloud SQL instance..."
      - gcloud sql instances patch paperterrace-db --activation-policy=ALWAYS
      - task: db:wait

  db:stop:
    desc: "Stop Cloud SQL instance (save cost)"
    cmds:
      - echo "⏹️ Stopping Cloud SQL instance..."
      - gcloud sql instances patch paperterrace-db --activation-policy=NEVER

  db:wait:
    desc: "Wait for Cloud SQL to be ready"
    cmds:
      - |
        echo "⏳ Waiting for Cloud SQL to be RUNNABLE..."
        for i in {1..6}; do
          STATUS=$(gcloud sql instances describe paperterrace-db --format="value(state)")
          echo "Current state: $STATUS"
          if [ "$STATUS" = "RUNNABLE" ]; then
            echo "✅ Cloud SQL is ready"
            exit 0
          fi
          sleep 30
        done
        echo "❌ Cloud SQL did not become RUNNABLE"
        exit 1

  db:migrate:
    desc: "Run database migrations"
    cmds:
      - echo "🔄 Running database migrations..."
      - uv run --directory backend alembic upgrade head

  # ============================================================================
  # Staging Environment Tasks
  # ============================================================================

  # ============================================================================
  # Infrastructure Tasks
  # ============================================================================

  # ============================================================================
  # Infrastructure Tasks
  # ============================================================================

  infra:init:production:
    desc: "Initialize Terraform for production"
    cmds:
      - echo "🔧 Initializing Terraform for production..."
      - unset GOOGLE_APPLICATION_CREDENTIALS && cd infrastructure/environments/production && terraform init

  infra:import:production:
    desc: "Import existing GCP resources into Terraform state (production)"
    cmds:
      - echo "📥 Importing existing resources to Terraform..."
      - unset GOOGLE_APPLICATION_CREDENTIALS && cd infrastructure/environments/production && terraform import -var="project_id={{.PROJECT_ID}}" -var="region={{.REGION}}" -var="gemini_api_key=${GEMINI_API_KEY}" -var="db_password=${DB_PASSWORD}" -var="image_url={{.REGION}}-docker.pkg.dev/{{.PROJECT_ID}}/paperterrace/app:latest" module.artifact_registry.google_artifact_registry_repository.main projects/{{.PROJECT_ID}}/locations/{{.REGION}}/repositories/paperterrace || echo "⚠️ Already imported or not found"
      - unset GOOGLE_APPLICATION_CREDENTIALS && cd infrastructure/environments/production && terraform import -var="project_id={{.PROJECT_ID}}" -var="region={{.REGION}}" -var="gemini_api_key=${GEMINI_API_KEY}" -var="db_password=${DB_PASSWORD}" -var="image_url={{.REGION}}-docker.pkg.dev/{{.PROJECT_ID}}/paperterrace/app:latest" module.iam.google_service_account.app_sa projects/{{.PROJECT_ID}}/serviceAccounts/paperterrace-sa@{{.PROJECT_ID}}.iam.gserviceaccount.com || echo "⚠️ Already imported or not found"
      - unset GOOGLE_APPLICATION_CREDENTIALS && cd infrastructure/environments/production && terraform import -var="project_id={{.PROJECT_ID}}" -var="region={{.REGION}}" -var="gemini_api_key=${GEMINI_API_KEY}" -var="db_password=${DB_PASSWORD}" -var="image_url={{.REGION}}-docker.pkg.dev/{{.PROJECT_ID}}/paperterrace/app:latest" module.networking.google_compute_network.main projects/{{.PROJECT_ID}}/global/networks/paperterrace-vpc || echo "⚠️ Already imported or not found"
      - echo "✅ Import complete!"

  infra:plan:production:
    desc: "Plan Terraform changes for production"
    cmds:
      - echo "📋 Planning Terraform changes for production..."
      - unset GOOGLE_APPLICATION_CREDENTIALS && cd infrastructure/environments/production && terraform plan -var="project_id={{.PROJECT_ID}}" -var="region={{.REGION}}" -var="gemini_api_key=${GEMINI_API_KEY}" -var="db_password=${DB_PASSWORD}" -var="image_url={{.REGION}}-docker.pkg.dev/{{.PROJECT_ID}}/paperterrace/app:latest"

  infra:apply:production:
    desc: "Apply Terraform changes for production"
    cmds:
      - echo "🚀 Applying Terraform changes for production..."
      - unset GOOGLE_APPLICATION_CREDENTIALS && cd infrastructure/environments/production && terraform apply -var="project_id={{.PROJECT_ID}}" -var="region={{.REGION}}" -var="gemini_api_key=${GEMINI_API_KEY}" -var="db_password=${DB_PASSWORD}" -var="image_url={{.REGION}}-docker.pkg.dev/{{.PROJECT_ID}}/paperterrace/app:latest"

  # ============================================================================
  # Utility Tasks
  # ============================================================================

  cleanup:
    desc: "Clean up unused Docker images and containers"
    cmds:
      - echo "🧹 Cleaning up Docker resources..."
      - docker system prune -f
      - echo "✅ Docker cleanup complete!"

  # ============================================================================
  # Helm Deployment Tasks
  # ============================================================================

  helm:deploy:
    desc: "Deploy PaperTerrace using Helm"
    cmds:
      - echo "🚀 Deploying with Helm..."
      - |
        VALUES_FILE="local-files/infrastructure/helm/paperterrace/values.yaml"
        [ -f "local-files/infrastructure/helm/paperterrace/values-dev.yaml" ] && VALUES_FILE_DEV="-f local-files/infrastructure/helm/paperterrace/values-dev.yaml"
        helm upgrade --install paperterrace ./infrastructure/helm/paperterrace \
          --namespace paperterrace \
          --create-namespace \
          -f "$VALUES_FILE" \
          ${VALUES_FILE_DEV:-}

  helm:undeploy:
    desc: "Undeploy PaperTerrace using Helm"
    cmds:
      - echo "🔥 Removing Helm release..."
      - helm uninstall paperterrace --namespace paperterrace

  helm:lint:
    desc: "Lint Helm chart"
    cmds:
      - helm lint ./infrastructure/helm/paperterrace

  # ============================================================================
  # Home Server (k3s) Deployment Tasks
  # ============================================================================

  k3s:secrets:
    desc: "Setup K8s secrets on home server"
    cmds:
      - ./scripts/create-secrets.sh

  k3s:deploy:
    desc: "Deploy all services to k3s using Helm"
    cmds:
      - task: helm:deploy

  k3s:status:
    desc: "Show status of k3s resources"
    cmds:
      - kubectl get pods,svc,deploy -n paperterrace

  k3s:logs:backend:
    desc: "View backend logs in k3s"
    cmds:
      - kubectl logs -f -l app=backend -n paperterrace

  k3s:logs:inference:
    desc: "View inference logs in k3s"
    cmds:
      - kubectl logs -f -l app=inference -n paperterrace

  k3s:restart:backend:
    desc: "Restart backend in k3s"
    cmds:
      - kubectl rollout restart deployment/backend -n paperterrace

  k3s:health:
    desc: "Check health of services in k3s"
    cmds:
      - echo "🔍 Checking service health..."
      - |
        echo "Backend:"
        kubectl exec -n paperterrace deployment/backend -- curl -s http://localhost:8080/api/health || echo "❌ Unhealthy"
        echo ""
        echo "Inference Server:"
        kubectl exec -n paperterrace deployment/inference -- curl -s http://localhost:8080/health || echo "❌ Unhealthy"
        echo ""
        echo "Redis:"
        kubectl exec -n paperterrace statefulset/paperterrace-redis-master -- redis-cli ping || echo "❌ Unhealthy"

  homeserver:health:
    desc: "Check health of all services"
    cmds:
      - task: k3s:health

  homeserver:build:
    desc: "Build Docker images for home server"
    env:
      REGISTRY: "{{.REGISTRY}}"
    cmds:
      - ./scripts/build-images.sh

  homeserver:deploy:
    desc: "Full deployment to home server (k3s)"
    cmds:
      - task: homeserver:build
      - task: k3s:secrets
      - task: k3s:deploy
      - echo "✅ Home server deployment complete!"

  homeserver:ps:
    desc: "Show status of all services"
    cmds:
      - task: k3s:status

  # ============================================================================
  # Cloudflare Deployment Tasks
  # ============================================================================

  cf:tunnel:setup:
    desc: "Setup Cloudflare Tunnel"
    cmds:
      - ./scripts/setup-tunnel.sh

  cf:tunnel:start:
    desc: "Start Cloudflare Tunnel (k3s)"
    cmds:
      - kubectl scale deployment/cloudflared --replicas=1 -n paperterrace

  cf:tunnel:logs:
    desc: "View Cloudflare Tunnel logs (k3s)"
    cmds:
      - kubectl logs -f -l app=cloudflared -n paperterrace

  cf:workers:install:
    desc: "Install all dependencies (including Workers/Frontend)"
    cmds:
      - npm install

  cf:workers:dev:
    desc: "Run Cloudflare Workers in development mode"
    cmds:
      - cd cloudflare-workers && npx wrangler dev

  cf:workers:deploy:
    desc: "Deploy Cloudflare Workers API Gateway"
    cmds:
      - cd cloudflare-workers && npx wrangler deploy

  cf:workers:secrets:
    desc: "Configure Cloudflare Workers secrets"
    cmds:
      - echo "Setting up Cloudflare Workers secrets..."
      - echo "Run these commands manually:"
      - echo "  npx wrangler secret put FIREBASE_PROJECT_ID"
      - echo "  npx wrangler secret put FIREBASE_CLIENT_EMAIL"
      - echo "  npx wrangler secret put FIREBASE_PRIVATE_KEY"

  cf:pages:deploy:
    desc: "Deploy frontend to Cloudflare Pages"
    cmds:
      - npm run build -w frontend
      - npx wrangler pages deploy frontend/dist --project-name paperterrace

  cf:deploy:
    desc: "Deploy all Cloudflare services (Workers + Pages)"
    cmds:
      - ./scripts/deploy-cloudflare.sh

  # ============================================================================
  # Migration Tasks
  # ============================================================================

  migrate:prepare:
    desc: "Prepare for migration to home server"
    cmds:
      - echo "📋 Migration preparation checklist:"
      - echo "1. ✓ Ensure .env file is configured"
      - echo "2. ✓ Ensure service account key is in secrets/sa-key.json"
      - echo "3. ✓ Ensure models are downloaded to ./models/"
      - echo "4. ✓ Ensure Cloudflare Tunnel is set up"
      - echo "5. ✓ Test home server deployment"
      - echo "6. ✓ Test Cloudflare Workers deployment"
      - echo "7. ✓ Verify end-to-end flow"

  migrate:test:
    desc: "Test new architecture"
    cmds:
      - echo "🧪 Testing new architecture..."
      - task: k3s:health
      - echo "Testing API Gateway..."
      - echo "Manual test required -- Visit Cloudflare Workers URL with valid token"

  migrate:switch:
    desc: "Switch traffic to new architecture"
    cmds:
      - echo "⚠️  This will switch traffic to the new architecture"
      - echo "Make sure you have tested thoroughly!"
      - echo "Update DNS to point to Cloudflare Pages"
      - echo "Monitor logs and metrics closely"
