export interface Stamp {
    id: string; // generated by backend or temp
    type: string; // e.g. '👍', '❓'
    x: number; // percentage (0-100) or pixels? Backend usually expects pixels or rel? 
    // Backend schema uses float x, y. Let's assume percentage for responsive design if possible, 
    // OR pixels relative to original image size. 
    // Existing logic used pageX/Y absolute.
    // For React implementation, percentage relative to the page image is best for responsiveness.
    y: number;
    page_number?: number;
    user_id?: string;
}

export type StampType = '👍' | '❓' | '💡' | '⚠️' | '⭐' | '🔥';

export const STAMP_TYPES: StampType[] = ['👍', '❓', '💡', '⚠️', '⭐', '🔥'];
