"""empty message

Revision ID: d5657bcdb262
Revises: 69b6d63210ec
Create Date: 2026-02-01 19:03:03.991772

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d5657bcdb262"
down_revision: Union[str, Sequence[str], None] = "69b6d63210ec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("app_sessions", schema=None) as batch_op:
        batch_op.alter_column(
            "session_id", existing_type=sa.TEXT(), type_=sa.String(), nullable=False
        )
        batch_op.alter_column(
            "paper_id", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True
        )
        batch_op.alter_column(
            "created_at",
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(),
            existing_nullable=True,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )

    with op.batch_alter_table("note_stamps", schema=None) as batch_op:
        batch_op.alter_column("id", existing_type=sa.TEXT(), type_=sa.String(), nullable=False)
        batch_op.alter_column(
            "note_id", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True
        )
        batch_op.alter_column(
            "user_id", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True
        )
        batch_op.alter_column(
            "stamp_type", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True
        )
        batch_op.alter_column(
            "x", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True
        )
        batch_op.alter_column(
            "y", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True
        )
        batch_op.alter_column(
            "created_at",
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(),
            existing_nullable=True,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )

    with op.batch_alter_table("notes", schema=None) as batch_op:
        batch_op.alter_column("note_id", existing_type=sa.TEXT(), type_=sa.String(), nullable=False)
        batch_op.alter_column(
            "session_id", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True
        )
        batch_op.alter_column(
            "term", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True
        )
        batch_op.alter_column(
            "image_url", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True
        )
        batch_op.alter_column(
            "user_id", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True
        )
        batch_op.alter_column(
            "x", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True
        )
        batch_op.alter_column(
            "y", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True
        )
        batch_op.alter_column(
            "created_at",
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(),
            existing_nullable=True,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )

    with op.batch_alter_table("ocr_reader", schema=None) as batch_op:
        batch_op.alter_column(
            "file_hash", existing_type=sa.TEXT(), type_=sa.String(), nullable=False
        )
        batch_op.alter_column(
            "filename", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True
        )
        batch_op.alter_column(
            "model_name", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True
        )
        batch_op.alter_column(
            "created_at",
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(),
            existing_nullable=True,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )

    with op.batch_alter_table("paper_figures", schema=None) as batch_op:
        batch_op.alter_column("id", existing_type=sa.TEXT(), type_=sa.String(), nullable=False)
        batch_op.alter_column(
            "paper_id", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True
        )
        batch_op.alter_column(
            "image_url", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True
        )
        batch_op.alter_column(
            "caption", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True
        )
        batch_op.alter_column(
            "label", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True
        )
        batch_op.alter_column(
            "created_at",
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(),
            existing_nullable=True,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )

    with op.batch_alter_table("paper_likes", schema=None) as batch_op:
        batch_op.add_column(sa.Column("updated_at", sa.DateTime(), nullable=True))
        batch_op.alter_column("user_id", existing_type=sa.TEXT(), type_=sa.String(), nullable=False)
        batch_op.alter_column(
            "paper_id", existing_type=sa.TEXT(), type_=sa.String(), nullable=False
        )
        batch_op.alter_column(
            "created_at",
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(),
            existing_nullable=True,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )

    with op.batch_alter_table("paper_stamps", schema=None) as batch_op:
        batch_op.alter_column("id", existing_type=sa.TEXT(), type_=sa.String(), nullable=False)
        batch_op.alter_column(
            "paper_id", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True
        )
        batch_op.alter_column(
            "user_id", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True
        )
        batch_op.alter_column(
            "stamp_type", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True
        )
        batch_op.alter_column(
            "x", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True
        )
        batch_op.alter_column(
            "y", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True
        )
        batch_op.alter_column(
            "created_at",
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(),
            existing_nullable=True,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )

    with op.batch_alter_table("papers", schema=None) as batch_op:
        batch_op.alter_column(
            "paper_id", existing_type=sa.TEXT(), type_=sa.String(), nullable=False
        )
        batch_op.alter_column(
            "file_hash", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True
        )
        batch_op.alter_column(
            "filename", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True
        )
        batch_op.alter_column(
            "target_language",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=True,
            existing_server_default=sa.text("'ja'"),
        )
        batch_op.alter_column(
            "owner_id", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True
        )
        batch_op.alter_column(
            "visibility",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=True,
            existing_server_default=sa.text("'private'"),
        )
        batch_op.alter_column(
            "title", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True
        )
        batch_op.alter_column(
            "authors", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True
        )
        batch_op.alter_column(
            "created_at",
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(),
            existing_nullable=True,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(),
            existing_nullable=True,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("plan", sa.String(), nullable=True))
        batch_op.alter_column("id", existing_type=sa.TEXT(), type_=sa.String(), nullable=False)
        batch_op.alter_column(
            "email", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False
        )
        batch_op.alter_column(
            "display_name", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True
        )
        batch_op.alter_column(
            "affiliation", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True
        )
        batch_op.alter_column(
            "profile_image_url", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True
        )
        batch_op.alter_column(
            "created_at",
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(),
            existing_nullable=True,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(),
            existing_nullable=True,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.DateTime(),
            type_=sa.TIMESTAMP(),
            existing_nullable=True,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DateTime(),
            type_=sa.TIMESTAMP(),
            existing_nullable=True,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )
        batch_op.alter_column(
            "profile_image_url", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True
        )
        batch_op.alter_column(
            "affiliation", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True
        )
        batch_op.alter_column(
            "display_name", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True
        )
        batch_op.alter_column(
            "email", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False
        )
        batch_op.alter_column("id", existing_type=sa.String(), type_=sa.TEXT(), nullable=True)
        batch_op.drop_column("plan")

    with op.batch_alter_table("papers", schema=None) as batch_op:
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.DateTime(),
            type_=sa.TIMESTAMP(),
            existing_nullable=True,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DateTime(),
            type_=sa.TIMESTAMP(),
            existing_nullable=True,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )
        batch_op.alter_column(
            "authors", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True
        )
        batch_op.alter_column(
            "title", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True
        )
        batch_op.alter_column(
            "visibility",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=True,
            existing_server_default=sa.text("'private'"),
        )
        batch_op.alter_column(
            "owner_id", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True
        )
        batch_op.alter_column(
            "target_language",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=True,
            existing_server_default=sa.text("'ja'"),
        )
        batch_op.alter_column(
            "filename", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True
        )
        batch_op.alter_column(
            "file_hash", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True
        )
        batch_op.alter_column("paper_id", existing_type=sa.String(), type_=sa.TEXT(), nullable=True)

    with op.batch_alter_table("paper_stamps", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DateTime(),
            type_=sa.TIMESTAMP(),
            existing_nullable=True,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )
        batch_op.alter_column(
            "y", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=True
        )
        batch_op.alter_column(
            "x", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=True
        )
        batch_op.alter_column(
            "stamp_type", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True
        )
        batch_op.alter_column(
            "user_id", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True
        )
        batch_op.alter_column(
            "paper_id", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True
        )
        batch_op.alter_column("id", existing_type=sa.String(), type_=sa.TEXT(), nullable=True)

    with op.batch_alter_table("paper_likes", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DateTime(),
            type_=sa.TIMESTAMP(),
            existing_nullable=True,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )
        batch_op.alter_column("paper_id", existing_type=sa.String(), type_=sa.TEXT(), nullable=True)
        batch_op.alter_column("user_id", existing_type=sa.String(), type_=sa.TEXT(), nullable=True)
        batch_op.drop_column("updated_at")

    with op.batch_alter_table("paper_figures", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DateTime(),
            type_=sa.TIMESTAMP(),
            existing_nullable=True,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )
        batch_op.alter_column(
            "label", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True
        )
        batch_op.alter_column(
            "caption", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True
        )
        batch_op.alter_column(
            "image_url", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True
        )
        batch_op.alter_column(
            "paper_id", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True
        )
        batch_op.alter_column("id", existing_type=sa.String(), type_=sa.TEXT(), nullable=True)

    with op.batch_alter_table("ocr_reader", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DateTime(),
            type_=sa.TIMESTAMP(),
            existing_nullable=True,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )
        batch_op.alter_column(
            "model_name", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True
        )
        batch_op.alter_column(
            "filename", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True
        )
        batch_op.alter_column(
            "file_hash", existing_type=sa.String(), type_=sa.TEXT(), nullable=True
        )

    with op.batch_alter_table("notes", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DateTime(),
            type_=sa.TIMESTAMP(),
            existing_nullable=True,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )
        batch_op.alter_column(
            "y", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=True
        )
        batch_op.alter_column(
            "x", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=True
        )
        batch_op.alter_column(
            "user_id", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True
        )
        batch_op.alter_column(
            "image_url", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True
        )
        batch_op.alter_column(
            "term", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True
        )
        batch_op.alter_column(
            "session_id", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True
        )
        batch_op.alter_column("note_id", existing_type=sa.String(), type_=sa.TEXT(), nullable=True)

    with op.batch_alter_table("note_stamps", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DateTime(),
            type_=sa.TIMESTAMP(),
            existing_nullable=True,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )
        batch_op.alter_column(
            "y", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=True
        )
        batch_op.alter_column(
            "x", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=True
        )
        batch_op.alter_column(
            "stamp_type", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True
        )
        batch_op.alter_column(
            "user_id", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True
        )
        batch_op.alter_column(
            "note_id", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True
        )
        batch_op.alter_column("id", existing_type=sa.String(), type_=sa.TEXT(), nullable=True)

    with op.batch_alter_table("app_sessions", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DateTime(),
            type_=sa.TIMESTAMP(),
            existing_nullable=True,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )
        batch_op.alter_column(
            "paper_id", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True
        )
        batch_op.alter_column(
            "session_id", existing_type=sa.String(), type_=sa.TEXT(), nullable=True
        )

    # ### end Alembic commands ###
